import { z } from 'zod';

// Metadata for any document stored in PersonaVault
export const DocumentMetadataSchema = z.object({
  title: z.string().min(1).nullish().describe('Title of the document'),
  source: z.string().min(1).describe('The source of the document (e.g., file name, URL)'),
  createdAt: z.string().datetime().nullish().describe('Creation timestamp of the original document'),
  tags: z.array(z.string().min(1)).min(0).nullish().describe('Tags or keywords associated with the document'),
  autogeneratedSummary: z.string().nullish().describe('A brief, AI-generated summary of the document'),
  // Retaining a flexible 'extra' field for any other metadata
  extra: z.record(z.any()).nullish().describe('Any other custom metadata'),
});

export type DocumentMetadata = z.infer<typeof DocumentMetadataSchema>;

// Schema for search filters
export const SearchFilterSchema = z.object({
  keywords: z.union([
    z.array(z.string()),
    z.string()
  ]).optional().describe('Keywords to filter by'),
  tags: z.union([
    z.array(z.string()),
    z.string()
  ]).optional().describe('Tags to filter by'),
  source: z.string().optional().describe('Source to filter by'),
  dateRange: z.object({
    start: z.string().datetime().optional(),
    end: z.string().datetime().optional()
  }).optional().describe('Date range to filter by'),
});

export type SearchFilter = z.infer<typeof SearchFilterSchema>;

// Interface for document chunks stored in the vector database
export interface DocumentChunk {
  id: string;
  text: string;
  metadata: DocumentMetadata & {
    sourceFile: string;
    chunkIndex: number;
    totalChunks: number;
  };
}

// Interface for search query results
export interface DocumentSearchResult {
  id: string;
  score: number;
  text: string;
  metadata: DocumentMetadata & {
    sourceFile: string;
    chunkIndex: number;
    totalChunks: number;
  };
} 